apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-web
spec:
  selector:
    matchLabels:
      app: client-web
  replicas: 1
  template:
    metadata:
      labels:
        run: client-web
    spec:
      containers:
      - name: client-web
        image: <dockerp-hub-account>/client-web:v0.1.0
        ports:
        - containerPort: 80
        - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: client-web
  labels:
    run: client-web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: client-web
